#!/usr/bin/env python3
import io, sys
from pathlib import Path

D = Path("/usr/local/src/rivermill/product-development/school-excursion/2026-08-10-how-the-river-day-was-decided/3-decisions")

J = {}
C = {}

J["card-0-one-offer-or-several.md"] = (
"**Joint:** Ruled with card 1 and read against cards 7, 13 and 22.",
"**Joint:** This card carries the structure and card 7 follows it. The two are one decision written twice, this card in the shape the buyer meets and card 7 in the money the quote states, and both recommend the compulsory base on the same evidence, the 48 of the 56 Australian profiles the two codings of the structure census place alike, where the base stands at 12 against the fixed programme's 8. The ruling order is settled here: whether a compulsory base exists at all is this card's own question, card 7 rules only how that structure is priced, and a base ruled away here leaves card 7 nothing to price. Card 7's Joint line says the same from its side. Where the two look opposite is in their third derivations, and that is a fact about which count each clerk read rather than about the market. This card's third took the day-shape axis, one day with a compulsory core and a choose-N inside it against pure choose-N, at 90 to 17 on the full corpus, and read the axis that separates the base from one fixed programme only as a narrow 59 to 51 of the 110 venues with usable school pricing. Card 7's third took that second axis as finding 28 reports it, 51 fixed to 39 base of the same 110, and landed on one fixed programme at one price, while computing the 59 to 51 the other way and saying in its own words that it cannot choose between the two splits from the market side. So the two verdicts are one census read on two axes, and both thirds agree that if the parameter is ruled to sell choice at all the base is all but settled, 39 to 17, 14 of 17 Australian and 7 of 7 on the resolved Queensland cell. Neither moves what either recommendation rests on, which is the Australian slice both codings place alike. Ruled with card 1 and read against cards 7, 13 and 22.",
)

J["card-7-price-structure.md"] = (
"**Joint:** Ruled with card 0 and with card 6.",
"**Joint:** Card 0 carries the structure and this card follows it. The two are one decision written twice, card 0 in the shape the buyer meets and this card in the money the quote states, and both recommend the compulsory base on the same evidence, the 48 of the 56 Australian profiles the two codings of the structure census place alike, where the base stands at 12 against the fixed price's 8. The ruling order is settled here: whether a compulsory base exists at all is card 0's own question, this card rules only how that structure is priced, and a base ruled away there leaves this card nothing to price. Card 0's Joint line says the same from its side. Where the two look opposite is in their third derivations, and that is a fact about which count each clerk read rather than about the market. This card's third took the axis that separates the base from one fixed programme as finding 28 reports it, 51 fixed to 39 base of the 110 venues with usable school pricing, and landed on one fixed programme at one price, while computing the buyer's two-way split at 59 to 51 the other way and saying in its own words that it cannot choose between the two splits from the market side. Card 0's third took the day-shape axis instead, one day with a compulsory core and a choose-N inside it against pure choose-N at 90 to 17 on the full corpus, and read the base-against-fixed lead as narrow. So the two verdicts are one census read on two axes, and both thirds agree that if the parameter is ruled to sell choice at all the base is all but settled, 39 to 17, 14 of 17 Australian and 7 of 7 on the resolved Queensland cell. Neither moves what either recommendation rests on, which is the Australian slice both codings place alike. Ruled with card 0 and with card 6.",
)

J["card-19-what-is-in-the-price.md"] = (
"**Joint:** Ruled with card 7, which sets whether there is a base at all,",
"**Joint:** This card carries the published food line and card 21 follows it. The two named each other and neither claimed the question, and the ruling order is settled here: what card 21 stands withheld between is a packed lunch with nothing sold to the school and a paid catering line published beside it, and what divides those two readings is whether a priced line is published where a buyer can read it, which is the whole of this card's question. Card 21's own instrument reaches the other half: its food count, 75 register-sample venues keeping food out of the school offer against 39 packaging it and 16 Australian to 2, excludes the packaging option and leaves its two live readings at 27 caterable venues publishing a paid line to 26 publishing none, a lead of one venue that one operator coded the other way erases. This card reaches the divider directly, on the structure census at 51 of 110 venues with usable school pricing selling one price with nothing beside it against 39 publishing priced components, and on the catchment's 20 day-excursion observations at the venues publishing the most lines against 2 at the one publishing a fixed untailorable programme. Card 21's Joint line says the same from its side. So a ruling here that publishes the lines settles card 21 with it, and card 21 is left with whether anything is sold to the school beside the permitted packed lunch at all, which the trial it already runs answers. Ruled with card 7, which sets whether there is a base at all,",
)

J["card-21-food.md"] = (
"**Joint:** Ruled with card 19, which decides whether food is a line on the invoice at all:",
"**Joint:** Card 19 carries the published food line and this card follows it. The two named each other and neither claimed the question, and the ruling order is settled here: what this card stands withheld between is a packed lunch with nothing sold to the school and a paid catering line published beside it, and what divides those two readings is whether a priced line is published where a buyer can read it, which is the whole of card 19's question. This card's own instrument reaches the other half: the food count of 75 register-sample venues keeping food out of the school offer against 39 packaging it and 16 Australian to 2 excludes the packaging option and leaves the two live readings at 27 caterable venues publishing a paid line to 26 publishing none, a lead of one venue that one operator coded the other way erases. Card 19 reaches the divider directly, on the structure census at 51 of 110 venues with usable school pricing selling one price with nothing beside it against 39 publishing priced components, and on the catchment's 20 day-excursion observations at the venues publishing the most lines against 2 at the one publishing a fixed untailorable programme. Card 19's Joint line says the same from its side. So the two readings this card is withheld between are not two answers to its own question: restated as the question this card is left with, they ask whether anything is sold to the school beside the permitted packed lunch at all, the basket and the platters, their existence and their price, which the trial running here since 14 August answers and which one sale settles; where the line is printed follows card 19. Ruled with card 19, which decides whether food is a line on the invoice at all:",
)

J["card-27-compliance-pack.md"] = (
"**Joint:** Decided with cards 23, 24 and 25 in mind and against them.",
"**Joint:** This card carries the pack and card 28 follows it. The familiarisation visit the owner ruled on 10 August 2026 sits inside this pack, so the two are one ruling seen twice, and the ruling order is settled here: what card 28 stands withheld between is a visit published on the page and no visit published with the paperwork going instead, and that is the channel this card's own question rules, what the pack holds, when it arrives and whether it travels with the quote or sits on the school page. This card's leg is the coded collection variable, 68 of 189 register-sample venues publishing a risk assessment against 121 publishing none and 68 against 7 among those stating any posture; card 28's is a whole-text sweep of the four pages collection read, which its own card calls a floor throughout and which cannot see a famil offered inside a returned quote, the very form the held value takes here. Card 28's Joint line says the same from its side. So a ruling here sets the channel for both: rule the pack published on the page and the famil inside it becomes visible to the instrument that cannot presently see it, and card 28 can be settled on a count; rule a thin pack or one sent only on request and the paperwork stops standing in for the visit there. The observations the two wait for are close kin and neither is the other: this card waits on a school naming the point in its approval chain at which it needed the documents in hand, card 28 on whether a school that booked a catchment rival was offered a famil inside the returned quote rather than on the page. Decided with cards 23, 24 and 25 in mind and against them.",
)

J["card-28-site-visit.md"] = (
"**Joint:** Ruled with card 27 and read against cards 23 and 29.",
"**Joint:** Card 27 carries the pack and this card follows it. The familiarisation visit the owner ruled on 10 August 2026 sits inside that pack, so the two are one ruling seen twice, and the ruling order is settled here: what this card stands withheld between is a visit published on the page and no visit published with the paperwork going instead, and that is the channel card 27's own question rules, what the pack holds, when it arrives and whether it travels with the quote or sits on the school page. Card 27's leg is the coded collection variable, 68 of 189 register-sample venues publishing a risk assessment against 121 publishing none and 68 against 7 among those stating any posture; this card's is a whole-text sweep of the four pages collection read, a floor throughout, which cannot see a famil offered inside a returned quote, the very form the held value takes here. Card 27's Joint line says the same from its side. So the two readings this card is withheld between are not two answers to its own question: restated as the question this card is left with, they ask whether a teacher visit is offered at all before the school commits, in whatever channel it is offered, the channel being card 27's to rule. The observations the two wait for are close kin and neither is the other: card 27 waits on a school naming the point in its approval chain at which it needed the documents in hand, this card on whether a school that booked a catchment rival was offered a famil inside the returned quote rather than on the page. Ruled with card 27 and read against cards 23 and 29.",
)

C["card-0-one-offer-or-several.md"] = " 2026-09-19, the collision pass. No count is corrected, the recommended line does not turn, and nothing it rests on is touched: the margin stays the 48 of 56 Australian profiles the two codings place alike, 12 to 8. What is settled is the collision with card 7, which answers the same question on the money side and whose third derivation landed on the opposite option. This card carries the structure and card 7 follows it, for the reason now on both Joint lines in the same words: whether a compulsory base exists at all is this card's own question and card 7 rules only how that structure is priced. What stood on the Joint line before was the clause that card 7 is the same decision seen from the money side and may not be ruled away from this one, which named the kinship and not the order, and it stands where it stood. Both Joint lines now also say which count each third derivation read, this card's the day-shape axis at 90 to 17 and card 7's the base-against-fixed axis at 51 to 39 of the same 110, so the opposite verdicts read as one census on two axes rather than as two markets."

C["card-7-price-structure.md"] = " 2026-09-19, the collision pass. No count is corrected, the recommended line does not turn, and nothing it rests on is touched: the margin stays the 48 of 56 Australian profiles the two codings place alike, 12 to 8. What is settled is the collision with card 0, which answers the same question on the offer side and whose third derivation landed on the opposite option to this card's. Card 0 carries the structure and this card follows it, for the reason now on both Joint lines in the same words: whether a compulsory base exists at all is card 0's own question and this card rules only how that structure is priced. What stood on the Joint line before was the clause that card 0 decides whether the buyer meets one offer or several and this is the same decision on the money side, which named the kinship and not the order, and it stands where it stood. Both Joint lines now also say which count each third derivation read, this card's the base-against-fixed axis at 51 to 39 of the 110 venues with usable school pricing and card 0's the day-shape axis at 90 to 17, so the opposite verdicts read as one census on two axes rather than as two markets."

C["card-19-what-is-in-the-price.md"] = " 2026-09-19, the collision pass. No count is corrected and the withheld line does not turn; the two readings, the counts they stand at and the observation that would carry either are untouched. What is settled is the collision with card 21. The two Joint lines named each other and neither claimed the question: this card's said only that a ruling at card 21 for food inside the price would narrow its option set, and card 21's said that a ruling here settles it. This card carries the published food line and card 21 follows it, for the reason now on both Joint lines in the same words: what divides card 21's two live readings is whether a priced line is published where a buyer can read it, which is this card's whole question, while card 21's own food count, 75 register-sample venues to 39, excludes only the packaging option and leaves those readings at 27 to 26, a lead one operator erases."

C["card-21-food.md"] = " 2026-09-19, the collision pass. No count is corrected and the withheld line does not turn; the two readings, the counts they stand at and the observation that would carry either are untouched. What is settled is the collision with card 19. The two Joint lines named each other and neither claimed the question: this card's said that a ruling at card 19 which publishes the lines settles this card with it, and card 19's said only that a ruling here for food inside the price would narrow its option set. Card 19 carries the published food line and this card follows it, for the reason now on both Joint lines in the same words: what divides this card's two live readings is whether a priced line is published where a buyer can read it, which is card 19's whole question, while this card's own food count, 75 register-sample venues to 39, excludes only the packaging option and leaves those readings at 27 to 26, a lead one operator erases. The Joint line now also restates the two readings as the question this card is left with, whether anything is sold to the school beside the permitted packed lunch at all; the Recommended line's readings and figures are as they were."

C["card-27-compliance-pack.md"] = " 2026-09-19, the collision pass. No count is corrected and the withheld line does not turn; the two readings, the counts they stand at and the observation that would carry either are untouched. What is settled is the collision with card 28. The dependency was written on one card only: card 28's Joint line said the two are one ruling seen twice, and this card's Joint line named cards 23, 24, 25 and 5 and did not name card 28 at all. This card carries the pack and card 28 follows it, for the reason now on both Joint lines in the same words: the ruled famil sits inside this pack, so the channel card 28 is withheld between is this card's own question, and this card reaches it on the coded collection variable at 68 of 189 against 121 while card 28's whole-text sweep is a floor that cannot see a famil offered inside a returned quote."

C["card-28-site-visit.md"] = " 2026-09-19, the collision pass. No count is corrected and the withheld line does not turn; the two readings, the counts they stand at and the observation that would carry either are untouched. What is settled is the collision with card 27, which this card's Joint line named while card 27's Joint line did not name this one. Card 27 carries the pack and this card follows it, for the reason now on both Joint lines in the same words: the ruled famil sits inside that pack, so the channel this card is withheld between is card 27's own question, and card 27 reaches it on the coded collection variable at 68 of 189 against 121 while this card's whole-text sweep is a floor that cannot see a famil offered inside a returned quote. The Joint line now also restates the two readings as the question this card is left with, whether a teacher visit is offered at all before the school commits; the Recommended line's readings and figures are as they were."

for fn in sorted(set(J) | set(C)):
    p = D / fn
    text = p.read_text()
    if fn in J:
        old, new = J[fn]
        assert text.count(old) == 1, (fn, "joint", text.count(old))
        text = text.replace(old, new)
    if fn in C:
        lines = text.split("\n")
        idx = [i for i, l in enumerate(lines) if l.startswith("**Corrections:**")]
        assert len(idx) == 1, (fn, "corrections", idx)
        lines[idx[0]] = lines[idx[0]].rstrip() + C[fn]
        text = "\n".join(lines)
    p.write_text(text)
    print("wrote", fn)
