-- Correspondence methodology plugin schema
-- PostgreSQL. Installs into the contact-graph database alongside the core
-- (public) tables. Dependencies point one way only: this plugin references
-- core (public.project, the generic item handle); core never references it,
-- so the whole plugin is droppable and the core stands alone.
--
-- Architecture and rationale: design.md. Agent behaviour: tend-methodology.md.

CREATE SCHEMA IF NOT EXISTS tend;

-- ---------------------------------------------------------------------------
-- Process definitions (loaded from the process folders, which are the source
-- of truth). The database copy exists for referential integrity, not as a
-- second place to author. Reloading replaces these rows from the folders.
-- ---------------------------------------------------------------------------

-- Valid states per process. The set of distinct `process` values here is the
-- list of installed processes; there is no separate registry table.
-- A two-state process (e.g. received -> filed) is as valid as a long lifecycle.
CREATE TABLE tend.process_state (
    process     TEXT    NOT NULL,   -- process key = folder name
    state       TEXT    NOT NULL,
    is_initial  BOOLEAN NOT NULL DEFAULT FALSE,
    is_terminal BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (process, state)
);

-- Valid transitions per process. rubric_ref points to the state--state
-- document in the process folder that carries the move's trigger and action.
CREATE TABLE tend.process_transition (
    process    TEXT NOT NULL,
    from_state TEXT NOT NULL,
    to_state   TEXT NOT NULL,
    rubric_ref TEXT,               -- path or name of the state--state document
    PRIMARY KEY (process, from_state, to_state),
    FOREIGN KEY (process, from_state) REFERENCES tend.process_state (process, state),
    FOREIGN KEY (process, to_state)   REFERENCES tend.process_state (process, state)
);

-- ---------------------------------------------------------------------------
-- Cases (the dynamic per-matter state)
-- ---------------------------------------------------------------------------

-- One row per matter. "case" is a SQL reserved word, so the table is quoted
-- everywhere it is referenced; the concept name is kept to match design.md.
-- project_id optionally links the matter to a contact-graph project; NULL is
-- the common case (most correspondence matters are not strategic projects).
-- The (process, current_state) foreign key guarantees a case is always in a
-- state its process declares. Removing a state from a process definition
-- therefore requires migrating any cases out of it first, which is the
-- intended discipline: a state nobody can leave should not be deleted.
CREATE TABLE tend."case" (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process       TEXT    NOT NULL,
    subject       TEXT,
    current_state TEXT    NOT NULL,
    project_id    INTEGER REFERENCES public.project (id),
    opened_at     INTEGER NOT NULL,   -- Unix timestamp
    updated_at    INTEGER,            -- Unix timestamp; last state change
    closed_at     INTEGER,            -- Unix timestamp; NULL = open
    FOREIGN KEY (process, current_state) REFERENCES tend.process_state (process, state)
);

CREATE INDEX idx_tend_case_process_state ON tend."case" (process, current_state);

-- Many-to-many link from a case to the messages that concern it. A message is
-- named by the generic (source_kind, external_item_id) handle that item_entity
-- already uses, not by a foreign key into a connector's tables, so a case can
-- absorb an email today and a chat message later without coupling to either
-- connector. The key is soft by design (no FK into a connector schema).
-- One message can belong to several cases; one case spans several messages.
CREATE TABLE tend.case_message (
    case_id          INTEGER NOT NULL REFERENCES tend."case" (id) ON DELETE CASCADE,
    source_kind      TEXT    NOT NULL,   -- e.g. 'email', 'whatsapp', 'chat'
    external_item_id TEXT    NOT NULL,   -- the message id within that source
    linked_at        INTEGER NOT NULL,   -- Unix timestamp
    PRIMARY KEY (case_id, source_kind, external_item_id)
);

CREATE INDEX idx_tend_case_message_item ON tend.case_message (source_kind, external_item_id);

-- Append-only log of state changes. This is the prior-action record the
-- Thread phase reads to see what was done with the previous message in a
-- matter. States are stored as plain text with no FK to process_state on
-- purpose: history must survive a later change to the process definition.
CREATE TABLE tend.case_transition (
    id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id                   INTEGER NOT NULL REFERENCES tend."case" (id) ON DELETE CASCADE,
    from_state                TEXT,               -- NULL for the opening entry
    to_state                  TEXT    NOT NULL,
    occurred_at               INTEGER NOT NULL,   -- Unix timestamp
    actor                     TEXT    NOT NULL,   -- 'director', 'ai', or an agent label
    evidence_source_kind      TEXT,               -- the message that triggered the move
    evidence_external_item_id TEXT,
    note                      TEXT
);

CREATE INDEX idx_tend_case_transition_case ON tend.case_transition (case_id, occurred_at);
