-- Contact Graph schema
-- PostgreSQL
-- Plugin-owned tables carry a "Plugin: <name>" comment.
-- Tables without that comment are generic / cross-plugin.

-- ---------------------------------------------------------------------------
-- People
-- ---------------------------------------------------------------------------

CREATE TABLE human (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name    TEXT    NOT NULL,
    linkedin_url    TEXT,
    internal        BOOLEAN NOT NULL DEFAULT FALSE,
    notes           TEXT
);

CREATE TABLE organisation (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  TEXT    NOT NULL,
    notes TEXT
);

-- ---------------------------------------------------------------------------
-- Email plugin
-- ---------------------------------------------------------------------------

-- Plugin: email
-- email_address defined before role to satisfy the FK dependency.
CREATE TABLE email_address (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address          TEXT    NOT NULL UNIQUE,
    human_id         INTEGER REFERENCES human (id),
    is_canonical     BOOLEAN NOT NULL DEFAULT FALSE,
    source           TEXT    NOT NULL,
    display_name_raw TEXT
);

-- A human holds a role at an organisation; the role owns its email address.
CREATE TABLE role (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    human_id         INTEGER NOT NULL REFERENCES human (id),
    title            TEXT,
    organisation_id  INTEGER REFERENCES organisation (id),
    email_address_id INTEGER REFERENCES email_address (id)
);

-- Plugin: email
-- Thread grouping from mu's Xapian index. thread_id is mu's internal
-- :thread-id, not a root message_id derived from References headers.
-- Outbound messages relayed via Amazon SES have their Message-ID rewritten
-- before delivery, so References-chain threading splits sent/reply pairs into
-- disconnected fragments. mu's subject-line normalisation fallback reconnects
-- them; this fallback cannot be reproduced without mu. See source-email.md §9.
--
-- status state machine: pending → done | error
-- priority_score: higher = process first during tail scan; scored from
--   known-human sender heuristic after harvest; 0 = not yet scored.
CREATE TABLE email_thread (
    thread_id         TEXT    NOT NULL PRIMARY KEY,
    first_message_at  INTEGER,           -- Unix timestamp
    last_message_at   INTEGER,           -- Unix timestamp
    last_processed_at INTEGER,           -- Unix timestamp; NULL = never processed
    status            TEXT    NOT NULL DEFAULT 'pending'
                              CHECK (status IN ('pending', 'done', 'error')),
    priority_score    DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    error_message     TEXT
);

-- Plugin: email
-- date anomalies: ~18 messages in the corpus have epoch (1970-01-01) or
-- far-future (year 2600+) dates from corrupted headers; the CHECK rejects
-- clearly invalid values.
-- thread_id is nullable: populated in Phase 2 after mu thread grouping;
-- NULL means the message has been harvested but not yet threaded.
CREATE TABLE email_message (
    message_id    TEXT    NOT NULL PRIMARY KEY,
    thread_id     TEXT    REFERENCES email_thread (thread_id),
    account       TEXT    NOT NULL,
    date          INTEGER NOT NULL CHECK (date > 0 AND date < 4102444800),
    date_anomaly  BOOLEAN NOT NULL DEFAULT FALSE,
    subject       TEXT
);

-- Plugin: email
-- One row per (thread, resolved human) pair. Populated by the thread worker
-- after identity resolution. A human appearing in 12 messages of a thread
-- still produces one row; roles[] accumulates all roles seen.
CREATE TABLE email_thread_participant (
    thread_id     TEXT    NOT NULL REFERENCES email_thread (thread_id),
    human_id      INTEGER NOT NULL REFERENCES human (id),
    roles         TEXT[]  NOT NULL DEFAULT '{}',
    first_seen_at INTEGER,  -- Unix timestamp
    PRIMARY KEY (thread_id, human_id)
);

-- Plugin: email
-- Addresses, domains, or regex patterns to exclude from graph ingestion.
--   address : exact address match
--   domain  : all addresses at this domain
--   subject : subject line contains this string
--   regex   : ~ match against the full address
CREATE TABLE email_ignored_pattern (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern      TEXT    NOT NULL,
    pattern_type TEXT    NOT NULL CHECK (pattern_type IN ('address', 'domain', 'subject', 'regex')),
    reason       TEXT    NOT NULL,
    UNIQUE (pattern, pattern_type)
);

-- Plugin: email
-- Cursor state for the per-account head/tail scan.
-- One row per active account. The meeting plugin does not use this table.
CREATE TABLE email_source_coverage (
    source_kind        TEXT    NOT NULL,
    source_ref         TEXT    NOT NULL,
    newest_scanned_id  TEXT,
    oldest_scanned_id  TEXT,
    last_checked_at    INTEGER,  -- Unix timestamp
    PRIMARY KEY (source_kind, source_ref)
);

-- Plugin: email
-- Bootstrap staging: candidate addresses from the mu corpus before identity
-- resolution. Populated once during initial import; cleared as candidates
-- are resolved to human records or confirmed as noise.
CREATE TABLE email_address_candidate (
    address           TEXT    NOT NULL PRIMARY KEY,
    display_name      TEXT    NOT NULL DEFAULT '',
    human_id_resolved INTEGER REFERENCES human (id)
);

-- ---------------------------------------------------------------------------
-- Meeting plugin
-- ---------------------------------------------------------------------------

-- Plugin: meeting
-- One row per attendee per meeting. Meetings have no sub-item structure so
-- this table is both the raw harvest log and the participant record.
-- identifier_ref: display name as written in the meeting heading.
CREATE TABLE meeting_participant (
    source_kind      TEXT    NOT NULL,
    external_item_id TEXT    NOT NULL,
    identifier_ref   TEXT    NOT NULL,
    role             TEXT    NOT NULL,
    UNIQUE (source_kind, external_item_id, identifier_ref, role)
);

-- ---------------------------------------------------------------------------
-- Derived graph edges (views, not stored tables)
-- ---------------------------------------------------------------------------
-- edge and coappearance are SQL views derived from plugin participant tables
-- (email_thread_participant, meeting_participant). Defined once all source
-- plugins are in place. Storing pre-aggregated copies destroys provenance.

-- ---------------------------------------------------------------------------
-- Tags
-- ---------------------------------------------------------------------------

CREATE TABLE tag (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label    TEXT    NOT NULL UNIQUE,
    category TEXT    NOT NULL
);

CREATE TABLE tag_evidence (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_id         INTEGER NOT NULL REFERENCES tag (id),
    source_type    TEXT    NOT NULL CHECK (source_type IN ('email', 'linkedin', 'manual')),
    identifier_ref TEXT    NOT NULL,
    source_item_id TEXT,
    date           INTEGER,
    snippet        TEXT,
    valid          BOOLEAN NOT NULL DEFAULT TRUE
);

-- ---------------------------------------------------------------------------
-- Projects
-- ---------------------------------------------------------------------------

CREATE TABLE project (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT    NOT NULL,
    type       TEXT    CHECK (type IN ('development', 'purchase', 'campaign', 'event', 'initiative', 'investigation', 'crisis')),
    status     TEXT    NOT NULL,
    started_at INTEGER
);

CREATE TABLE project_human (
    project_id INTEGER NOT NULL REFERENCES project (id),
    human_id   INTEGER NOT NULL REFERENCES human (id),
    reason     TEXT,
    added_at   INTEGER,
    PRIMARY KEY (project_id, human_id)
);

CREATE TABLE project_tag (
    project_id INTEGER NOT NULL REFERENCES project (id),
    tag_id     INTEGER NOT NULL REFERENCES tag (id),
    added_at   INTEGER,
    PRIMARY KEY (project_id, tag_id)
);

-- ---------------------------------------------------------------------------
-- Body-level entity extraction
-- ---------------------------------------------------------------------------

-- Named entities extracted from item bodies by AI.
-- Answers "what did this item discuss?" rather than "who participated?"
-- FK columns populated by a post-extraction resolution pass.
-- Defined after project to satisfy FK dependency.
CREATE TABLE item_entity (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_kind      TEXT    NOT NULL,
    external_item_id TEXT    NOT NULL,
    entity_type      TEXT    NOT NULL CHECK (entity_type IN (
                         'person_mentioned', 'organisation', 'project', 'product', 'domain')),
    value            TEXT    NOT NULL,
    context          TEXT,
    human_id         INTEGER REFERENCES human (id),
    organisation_id  INTEGER REFERENCES organisation (id),
    project_id       INTEGER REFERENCES project (id),
    extracted_at     INTEGER,
    UNIQUE (source_kind, external_item_id, entity_type, value)
);

-- ---------------------------------------------------------------------------
-- LinkedIn enrichment
-- ---------------------------------------------------------------------------

CREATE TABLE linkedin_snapshot (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    human_id    INTEGER NOT NULL REFERENCES human (id),
    scraped_at  INTEGER NOT NULL,
    url         TEXT    NOT NULL,
    headline    TEXT,
    location    TEXT,
    summary     TEXT
);

CREATE TABLE human_event (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    human_id           INTEGER NOT NULL REFERENCES human (id),
    event_type         TEXT    NOT NULL,
    description        TEXT,
    source_snapshot_id INTEGER REFERENCES linkedin_snapshot (id),
    event_date         TEXT    NOT NULL
);

CREATE TABLE linkedin_connection (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    human_id_a              INTEGER REFERENCES human (id),
    linkedin_url_a          TEXT    NOT NULL,
    human_id_b              INTEGER REFERENCES human (id),
    linkedin_url_b          TEXT    NOT NULL,
    discovered_via_human_id INTEGER REFERENCES human (id),
    scraped_at              INTEGER NOT NULL,
    UNIQUE (linkedin_url_a, linkedin_url_b)
);

-- ---------------------------------------------------------------------------
-- Processing queue and decay scheduler
-- ---------------------------------------------------------------------------

CREATE TABLE processing_queue (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    human_id       INTEGER NOT NULL REFERENCES human (id),
    job_type       TEXT    NOT NULL CHECK (job_type IN ('tag', 'linkedin')),
    priority_score DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    queued_at      INTEGER NOT NULL,
    processed_at   INTEGER,
    model_used     TEXT
);

CREATE TABLE reconnect_schedule (
    human_id         INTEGER NOT NULL PRIMARY KEY REFERENCES human (id),
    next_prompt_date TEXT    NOT NULL,
    last_prompted_at TEXT,
    computed_at      INTEGER
);
