-- Contact Graph schema
-- PostgreSQL
-- Plugin-owned tables carry a "Plugin: <name>" comment.
-- Tables without that comment are generic / cross-plugin.

CREATE SCHEMA linkedin;

-- ---------------------------------------------------------------------------
-- People
-- ---------------------------------------------------------------------------

CREATE TABLE human (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name    TEXT    NOT NULL,
    internal        BOOLEAN NOT NULL DEFAULT FALSE,
    notes           TEXT
);

CREATE TABLE organisation (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  TEXT    NOT NULL,
    notes TEXT
);

-- ---------------------------------------------------------------------------
-- LinkedIn plugin
-- ---------------------------------------------------------------------------

-- Plugin: linkedin
-- slug is globally unique on LinkedIn; URL = linkedin.com/in/<slug>.
-- human_id is nullable: a profile row may be created before identity resolution.
-- urn (urn:li:member:...) is nullable: not always obtainable from a public page.
-- Internal humans (human.internal = TRUE) with a profile row are the operator's
-- LinkedIn accounts; no separate account table is needed.
CREATE TABLE linkedin.profile (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    human_id INTEGER REFERENCES human (id),
    slug     TEXT    NOT NULL UNIQUE,
    urn      TEXT
);

-- Plugin: linkedin
-- Versioned profile captures: one row each time a profile's display attributes
-- are observed (a data export, a live fetch). Retained in full rather than
-- overwritten, so life-change events (role moves, relocations) are derivable by
-- diffing successive rows. Columns are nullable because sources expose
-- different fields: the connections export carries raw_name, company and title;
-- the self-profile export carries headline, summary, industry and location.
-- Promotion to structured form (company -> organisation, title -> role) is a
-- later resolution pass; this table holds the verbatim capture. Email is not
-- here: an observed address belongs in the core email_address table.
CREATE TABLE linkedin.profile_snapshot (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id  INTEGER NOT NULL REFERENCES linkedin.profile (id),
    captured_at INTEGER NOT NULL,   -- Unix timestamp of the observation
    source      TEXT    NOT NULL,
    raw_name    TEXT,
    headline    TEXT,
    company     TEXT,
    title       TEXT,
    location    TEXT,
    industry    TEXT,
    summary     TEXT,
    UNIQUE (profile_id, source, captured_at)
);

-- Plugin: linkedin
-- First-degree connections between two LinkedIn profiles. from_profile_id is
-- always a profile belonging to an internal human (the operator's account).
CREATE TABLE linkedin.connection (
    from_profile_id INTEGER NOT NULL REFERENCES linkedin.profile (id),
    to_profile_id   INTEGER NOT NULL REFERENCES linkedin.profile (id),
    connected_at    INTEGER,   -- Unix timestamp; NULL when LinkedIn withholds the date
    discovered_at   INTEGER NOT NULL,
    PRIMARY KEY (from_profile_id, to_profile_id)
);

-- Plugin: linkedin
-- One row per (human, campaign). The state column drains the row through the
-- pipeline: candidate -> verified|unverifiable|ambiguous -> drafted -> queued
-- -> sent -> accepted|declined|expired|failed. do_not_contact is reachable
-- from any non-terminal state as a manual override; the reason lives in
-- exclusion_reason. profile_id is nullable because candidate and non-verified
-- rows have no profile yet.
CREATE TABLE linkedin.connection_queue (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    human_id          INTEGER NOT NULL REFERENCES human (id) ON DELETE CASCADE,
    workflow_label    TEXT    NOT NULL DEFAULT 'linkedin_2026',
    state             TEXT    NOT NULL CHECK (state IN (
                          'candidate', 'verifying', 'verified',
                          'unverifiable', 'ambiguous',
                          'drafted', 'queued',
                          'sent', 'accepted', 'declined', 'expired',
                          'failed', 'do_not_contact',
                          'already_connected', 'invite_pending'
                      )),
    priority          DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    profile_id        INTEGER REFERENCES linkedin.profile (id),
    note_text         TEXT,
    with_note         BOOLEAN,
    verify_evidence   JSONB,
    failure_reason    TEXT,
    exclusion_reason  TEXT,
    level             SMALLINT,
    queued_at         INTEGER NOT NULL,
    verified_at       INTEGER,
    drafted_at        INTEGER,
    sent_at           INTEGER,
    terminal_at       INTEGER,
    UNIQUE (human_id, workflow_label)
);

-- ---------------------------------------------------------------------------
-- Email plugin
-- ---------------------------------------------------------------------------

-- Plugin: email
-- email_address defined before role to satisfy the FK dependency.
CREATE TABLE email_address (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address          TEXT    NOT NULL UNIQUE,
    human_id         INTEGER REFERENCES human (id),
    is_canonical     BOOLEAN NOT NULL DEFAULT FALSE,
    source           TEXT    NOT NULL,
    display_name_raw TEXT
);

-- Plugin: email
-- Thread grouping from mu's Xapian index. thread_id is mu's internal
-- :thread-id, not a root message_id derived from References headers.
-- Outbound messages relayed via Amazon SES have their Message-ID rewritten
-- before delivery, so References-chain threading splits sent/reply pairs into
-- disconnected fragments. mu's subject-line normalisation fallback reconnects
-- them; this fallback cannot be reproduced without mu. See source-email.md §9.
--
-- status state machine: pending → done | error
-- priority_score: higher = process first during tail scan; scored from
--   known-human sender heuristic after ingest; 0 = not yet scored.
CREATE TABLE email_thread (
    thread_id         TEXT    NOT NULL PRIMARY KEY,
    first_message_at  INTEGER,           -- Unix timestamp
    last_message_at   INTEGER,           -- Unix timestamp
    last_processed_at INTEGER,           -- Unix timestamp; NULL = never processed
    status            TEXT    NOT NULL DEFAULT 'pending'
                              CHECK (status IN ('pending', 'done', 'error')),
    priority_score    DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    error_message     TEXT
);

-- Plugin: email
-- date anomalies: ~18 messages in the corpus have epoch (1970-01-01) or
-- far-future (year 2600+) dates from corrupted headers; the CHECK rejects
-- clearly invalid values.
-- thread_id is nullable: populated in Phase 2 after mu thread grouping;
-- NULL means the message has been ingested but not yet threaded.
CREATE TABLE email_message (
    message_id    TEXT    NOT NULL PRIMARY KEY,
    thread_id     TEXT    REFERENCES email_thread (thread_id),
    account       TEXT    NOT NULL,
    date          INTEGER NOT NULL CHECK (date > 0 AND date < 4102444800),
    date_anomaly  BOOLEAN NOT NULL DEFAULT FALSE,
    subject       TEXT,
    is_spam       BOOLEAN NOT NULL DEFAULT FALSE
);

-- Plugin: email
-- One row per (thread, resolved human) pair. Populated by the thread worker
-- after identity resolution. A human appearing in 12 messages of a thread
-- still produces one row; roles[] accumulates all roles seen.
CREATE TABLE email_thread_participant (
    thread_id     TEXT    NOT NULL REFERENCES email_thread (thread_id),
    human_id      INTEGER NOT NULL REFERENCES human (id),
    roles         TEXT[]  NOT NULL DEFAULT '{}',
    first_seen_at INTEGER,  -- Unix timestamp
    PRIMARY KEY (thread_id, human_id)
);

-- Plugin: email
-- Addresses, domains, or regex patterns to exclude from graph ingestion.
--   address : exact address match
--   domain  : all addresses at this domain
--   subject : subject line contains this string
--   regex   : ~ match against the full address
CREATE TABLE email_ignored_pattern (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern      TEXT    NOT NULL,
    pattern_type TEXT    NOT NULL CHECK (pattern_type IN ('address', 'domain', 'subject', 'regex')),
    reason       TEXT    NOT NULL,
    UNIQUE (pattern, pattern_type)
);

-- Plugin: email
-- Cursor state for the per-account head/tail scan.
-- One row per active account. The meeting plugin does not use this table.
CREATE TABLE email_source_coverage (
    source_kind        TEXT    NOT NULL,
    source_ref         TEXT    NOT NULL,
    newest_scanned_id  TEXT,
    oldest_scanned_id  TEXT,
    last_checked_at    INTEGER,  -- Unix timestamp
    PRIMARY KEY (source_kind, source_ref)
);

-- Plugin: email
-- Bootstrap staging: candidate addresses from the mu corpus before identity
-- resolution. Populated once during initial import; cleared as candidates
-- are resolved to human records or confirmed as noise.
CREATE TABLE email_address_candidate (
    address           TEXT    NOT NULL PRIMARY KEY,
    display_name      TEXT    NOT NULL DEFAULT '',
    human_id_resolved INTEGER REFERENCES human (id)
);

-- Plugin: email indexes for ingest pipeline performance
CREATE INDEX idx_email_message_thread_id ON email_message (thread_id);
CREATE INDEX idx_email_thread_status ON email_thread (status)
    WHERE status = 'pending';

-- ---------------------------------------------------------------------------
-- Derived graph edges (views, not stored tables)
-- ---------------------------------------------------------------------------
-- edge and coappearance are SQL views derived from plugin participant tables
-- (email_thread_participant, meeting_participant). Defined once all source
-- plugins are in place. Storing pre-aggregated copies destroys provenance.

-- ---------------------------------------------------------------------------
-- Projects
-- ---------------------------------------------------------------------------

CREATE TABLE project (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT    NOT NULL,
    type       TEXT    CHECK (type IN ('development', 'purchase', 'campaign', 'event', 'initiative', 'investigation', 'crisis')),
    status     TEXT    NOT NULL,
    started_at INTEGER
);

-- ---------------------------------------------------------------------------
-- Body-level entity extraction
-- ---------------------------------------------------------------------------

-- Named entities extracted from item bodies by AI.
-- Answers "what did this item discuss?" rather than "who participated?"
-- FK columns populated by a post-extraction resolution pass.
-- Defined after project to satisfy FK dependency.
CREATE TABLE item_entity (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_kind      TEXT    NOT NULL,
    external_item_id TEXT    NOT NULL,
    entity_type      TEXT    NOT NULL CHECK (entity_type IN (
                         'person_mentioned', 'organisation', 'project', 'product', 'domain')),
    value            TEXT    NOT NULL,
    context          TEXT,
    human_id         INTEGER REFERENCES human (id),
    organisation_id  INTEGER REFERENCES organisation (id),
    project_id       INTEGER REFERENCES project (id),
    extracted_at     INTEGER,
    UNIQUE (source_kind, external_item_id, entity_type, value)
);

-- Plugin: email
-- Tracks which messages have been through entity extraction.
-- Separates "processed, nothing found" (empty) from "not yet processed"
-- (no row), enabling budget-controlled runs to resume without reprocessing.
CREATE TABLE email_extraction_log (
    message_id   TEXT    NOT NULL PRIMARY KEY REFERENCES email_message (message_id),
    status       TEXT    NOT NULL CHECK (status IN ('done', 'empty', 'error', 'skipped')),
    extracted_at INTEGER NOT NULL,
    tokens_in    INTEGER,
    tokens_out   INTEGER,
    error_detail TEXT
);
